language: php

services:
    - mysql

env:
    global:
        - DATABASE_URL=mysql://root:@127.0.0.1:3306/test
        - APP_ENV=test

php:
    - 7.2

install:
    - composer install
    - composer global require phpunit/phpunit

script:
    - phpunit
