#System author
# DO NOT CHANGE!
author: v18
author_link: https://github.com/v18-team/
software_version: 1.0 ALPHA
# DO NOT CHANGE
#semantic page language
page_language: pl
#Product name. You can view it at homepage
product_name: SummaDocs
